### ISSUE TITLE
Prohozené signály u Flash paměti

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/PROGLOG01#1]
Je potřeba zkontrolovat, jestli je to opravené i v layoutu a vytvořit revizi B. 

![DSC01620](https://user-images.githubusercontent.com/1194177/202148383-537c1975-1d8c-40ad-9006-534c34a9db95.JPG)

**Comment by povik** [comment]
Neni to opravené.

**Comment by kaklik** [comment]
Pokusil jsem se v [datasheetu](https://www.latticesemi.com/-/media/LatticeSemi/Documents/DataSheets/iCE/FPGA-DS-02008-1-9-iCE40-UltraPlus-Family-Data-Sheet.ashx?document_id=51968) najít, jaký je pinout konfiguračního SPI rozhraní, které má být připojeno k SPI flash. 

Nepodařilo se mi však najít více než tohle, což neobjasňuje proč jsou nyní piny zapojeny špatně. Současné zapojení ale odpovídá popiskům nožiček na schématických značkách. Tudíž očekávám že k opravě chyby je potřeba opravit schematickou značku FPGA, neboť schematická značka SPI flash je správně. To jsem již podle datasheetu zkontroloval.

![image](https://user-images.githubusercontent.com/1194177/202200656-fe4cf9f6-ff36-4956-a0dd-d8a038257270.png)

Chěl jsem to opravit, aby bylo možné vyrobit více kusů modulů a celý další vývoj nestál pouze na existujících dvou kusech.

**Comment by kaklik** [comment]
@povik  Tak jsem to myslím si opravil. Mohl bys akorát prosím zkontrolovat, že je to opravené dobře? Na fotografii totiž jsou celkem tři provizorní drátky, ale našel jsem jen dvě prohozená místa. Třetí myslím vede na stejný pin jako původní cestička. To byla nějaká chyba při změně zapojení?

**Comment by povik** [comment]
Jo, prohozené ve schématu 01A jsou jen dva dráty u paměti (MISO/MOSI). Že jsou na tom operovaném kusu tři drátky, bude kvůli nějakému omylu při přepojování.

> Tudíž očekávám že k opravě chyby je potřeba opravit schematickou značku FPGA, neboť schematická značka SPI flash je správně.

Jak tohle dopadlo? Čekám, že to byla chyba ve schématu, né ve značce, tak si to pamatuju.

**Comment by kaklik** [comment]
> > Tudíž očekávám že k opravě chyby je potřeba opravit schematickou značku FPGA, neboť schematická značka SPI flash je správně.
> 
> Jak tohle dopadlo? Čekám, že to byla chyba ve schématu, né ve značce, tak si to pamatuju.

S tímhle to teď je tak, že ta schématická značka FPGA je neopravená. Tj. je pravděpodobně špatně název pinu ve schématické značce. Kontroloval jsem to podle čísla pinu, které je myslím si správně.

**Comment by povik** [comment]
> S tímhle to teď je tak, že ta schématická značka FPGA je neopravená. Tj. je pravděpodobně špatně název pinu ve schématické značce. Kontroloval jsem to podle čísla pinu, které je myslím si správně.

Ne, já myslim, že značka je správně. Jen je matoucí, že pin SI/SO na součástce hradlovýho pole znamená Serial In/Out, nikoliv Slave In/Out, takže se to s pamětí musí zapojit křížem. To je původ toho omylu ve schématu.

**Comment by kaklik** [comment]
> Ne, já myslim, že značka je správně. Jen je matoucí, že pin SI/SO na součástce hradlovýho pole znamená Serial In/Out, nikoliv Slave In/Out, takže se to s pamětí musí zapojit křížem. To je původ toho omylu ve schématu.

Aha, tak to je opravdu matoucí.  To by si možná zasloužilo nějakou poznámku do schéma. Protože se to děsně blbě ověřuje. V datasheetu jsem totiž tohle našel jen na jednom místě a nedošlo mi z toho, že to není chyba v datasheetu.
